# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/add_profile_class.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_AddProfileClass(object):
    def setupUi(self, AddProfileClass):
        AddProfileClass.setObjectName("AddProfileClass")
        AddProfileClass.resize(196, 127)
        self.gridLayout_4 = QtWidgets.QGridLayout(AddProfileClass)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_question = QtWidgets.QLabel(AddProfileClass)
        self.label_question.setObjectName("label_question")
        self.gridLayout_4.addWidget(self.label_question, 0, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_3.addItem(spacerItem, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(AddProfileClass)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(AddProfileClass)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.spinBox_from = QtWidgets.QSpinBox(AddProfileClass)
        self.spinBox_from.setObjectName("spinBox_from")
        self.gridLayout.addWidget(self.spinBox_from, 1, 0, 1, 1)
        self.spinBox_to = QtWidgets.QSpinBox(AddProfileClass)
        self.spinBox_to.setObjectName("spinBox_to")
        self.gridLayout.addWidget(self.spinBox_to, 1, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(AddProfileClass)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 0, 1, 1)

        self.retranslateUi(AddProfileClass)
        QtCore.QMetaObject.connectSlotsByName(AddProfileClass)

    def retranslateUi(self, AddProfileClass):
        _translate = QtCore.QCoreApplication.translate
        AddProfileClass.setWindowTitle(_translate("AddProfileClass", "Add Profile Classifier"))
        self.label_question.setText(_translate("AddProfileClass", "TextLabel"))
        self.label.setText(_translate("AddProfileClass", "ОТ"))
        self.label_2.setText(_translate("AddProfileClass", "ДО"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    AddProfileClass = QtWidgets.QWidget()
    ui = Ui_AddProfileClass()
    ui.setupUi(AddProfileClass)
    AddProfileClass.show()
    sys.exit(app.exec_())
