# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\geovel_1.0\qt\add_well_dialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_add_well(object):
    def setupUi(self, add_well):
        add_well.setObjectName("add_well")
        add_well.resize(400, 112)
        self.gridLayout_3 = QtWidgets.QGridLayout(add_well)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit_well_name = QtWidgets.QLineEdit(add_well)
        self.lineEdit_well_name.setObjectName("lineEdit_well_name")
        self.gridLayout.addWidget(self.lineEdit_well_name, 0, 1, 1, 1)
        self.label = QtWidgets.QLabel(add_well)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.toolButton_del = QtWidgets.QToolButton(add_well)
        self.toolButton_del.setEnabled(True)
        self.toolButton_del.setStyleSheet("background-color: rgb(255, 185, 185);")
        self.toolButton_del.setObjectName("toolButton_del")
        self.gridLayout.addWidget(self.toolButton_del, 0, 2, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_2 = QtWidgets.QLabel(add_well)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.lineEdit_well_x = QtWidgets.QLineEdit(add_well)
        self.lineEdit_well_x.setObjectName("lineEdit_well_x")
        self.gridLayout_2.addWidget(self.lineEdit_well_x, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(add_well)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout_2.addWidget(self.label_3, 0, 2, 1, 1)
        self.lineEdit_well_y = QtWidgets.QLineEdit(add_well)
        self.lineEdit_well_y.setObjectName("lineEdit_well_y")
        self.gridLayout_2.addWidget(self.lineEdit_well_y, 0, 3, 1, 1)
        self.label_4 = QtWidgets.QLabel(add_well)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 1, 0, 1, 1)
        self.lineEdit_well_alt = QtWidgets.QLineEdit(add_well)
        self.lineEdit_well_alt.setObjectName("lineEdit_well_alt")
        self.gridLayout_2.addWidget(self.lineEdit_well_alt, 1, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(add_well)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.buttonBox.setFont(font)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 2, 1, 2)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 0, 1, 1)

        self.retranslateUi(add_well)
        QtCore.QMetaObject.connectSlotsByName(add_well)

    def retranslateUi(self, add_well):
        _translate = QtCore.QCoreApplication.translate
        add_well.setWindowTitle(_translate("add_well", "Добавить скважину"))
        self.label.setText(_translate("add_well", "Номер скважины:"))
        self.toolButton_del.setText(_translate("add_well", "del"))
        self.label_2.setText(_translate("add_well", "X:"))
        self.label_3.setText(_translate("add_well", "Y:"))
        self.label_4.setText(_translate("add_well", "Alt:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    add_well = QtWidgets.QWidget()
    ui = Ui_add_well()
    ui.setupUi(add_well)
    add_well.show()
    sys.exit(app.exec_())
