# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/anova_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Anova(object):
    def setupUi(self, Anova):
        Anova.setObjectName("Anova")
        Anova.resize(1600, 1080)
        self.gridLayout = QtWidgets.QGridLayout(Anova)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(Anova)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listWidget = QtWidgets.QListWidget(self.frame_2)
        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_3.addWidget(self.listWidget)
        self.listWidget_checkbox_well = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_checkbox_well.setObjectName("listWidget_checkbox_well")
        self.horizontalLayout_3.addWidget(self.listWidget_checkbox_well)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_strip = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_strip.setObjectName("radioButton_strip")
        self.verticalLayout.addWidget(self.radioButton_strip)
        self.radioButton_box = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_box.setObjectName("radioButton_box")
        self.verticalLayout.addWidget(self.radioButton_box)
        self.radioButton_boxen = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_boxen.setChecked(True)
        self.radioButton_boxen.setObjectName("radioButton_boxen")
        self.verticalLayout.addWidget(self.radioButton_boxen)
        self.radioButton_violin = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_violin.setObjectName("radioButton_violin")
        self.verticalLayout.addWidget(self.radioButton_violin)
        self.horizontalLayout_3.addWidget(self.frame_3)
        self.horizontalLayout_3.setStretch(0, 2)
        self.horizontalLayout_3.setStretch(2, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(Anova)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(Anova)
        QtCore.QMetaObject.connectSlotsByName(Anova)

    def retranslateUi(self, Anova):
        _translate = QtCore.QCoreApplication.translate
        Anova.setWindowTitle(_translate("Anova", "ANOVA"))
        self.radioButton_strip.setText(_translate("Anova", "StripPlot"))
        self.radioButton_box.setText(_translate("Anova", "BoxPlot"))
        self.radioButton_boxen.setText(_translate("Anova", "BoxenPlot"))
        self.radioButton_violin.setText(_translate("Anova", "ViolinPlot"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Anova = QtWidgets.QWidget()
    ui = Ui_Anova()
    ui.setupUi(Anova)
    Anova.show()
    sys.exit(app.exec_())
