# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/calc_object.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_calc_object(object):
    def setupUi(self, Dialog_calc_object):
        Dialog_calc_object.setObjectName("Dialog_calc_object")
        Dialog_calc_object.resize(562, 261)
        self.widget = QtWidgets.QWidget(Dialog_calc_object)
        self.widget.setGeometry(QtCore.QRect(10, 10, 541, 235))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.listWidget_objects = QtWidgets.QListWidget(self.widget)
        self.listWidget_objects.setObjectName("listWidget_objects")
        self.verticalLayout.addWidget(self.listWidget_objects)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.pushButton_calc_cls = QtWidgets.QPushButton(self.widget)
        self.pushButton_calc_cls.setStyleSheet("background-color: rgb(214, 206, 255);")
        self.pushButton_calc_cls.setObjectName("pushButton_calc_cls")
        self.horizontalLayout_2.addWidget(self.pushButton_calc_cls)
        self.pushButton_calc_reg = QtWidgets.QPushButton(self.widget)
        self.pushButton_calc_reg.setStyleSheet("background-color: rgb(205, 205, 103);")
        self.pushButton_calc_reg.setObjectName("pushButton_calc_reg")
        self.horizontalLayout_2.addWidget(self.pushButton_calc_reg)
        self.pushButton_start_co = QtWidgets.QPushButton(self.widget)
        self.pushButton_start_co.setStyleSheet("background-color: rgb(255, 248, 165);")
        self.pushButton_start_co.setObjectName("pushButton_start_co")
        self.horizontalLayout_2.addWidget(self.pushButton_start_co)
        self.pushButton_delete_co = QtWidgets.QPushButton(self.widget)
        self.pushButton_delete_co.setStyleSheet("background-color: rgb(255, 165, 165);")
        self.pushButton_delete_co.setObjectName("pushButton_delete_co")
        self.horizontalLayout_2.addWidget(self.pushButton_delete_co)
        self.pushButton_clear_co = QtWidgets.QPushButton(self.widget)
        self.pushButton_clear_co.setStyleSheet("background-color: rgb(194, 194, 194);")
        self.pushButton_clear_co.setObjectName("pushButton_clear_co")
        self.horizontalLayout_2.addWidget(self.pushButton_clear_co)
        self.verticalLayout.addLayout(self.horizontalLayout_2)

        self.retranslateUi(Dialog_calc_object)
        QtCore.QMetaObject.connectSlotsByName(Dialog_calc_object)

    def retranslateUi(self, Dialog_calc_object):
        _translate = QtCore.QCoreApplication.translate
        Dialog_calc_object.setWindowTitle(_translate("Dialog_calc_object", "Dialog"))
        self.pushButton_calc_cls.setText(_translate("Dialog_calc_object", "ADD CLS"))
        self.pushButton_calc_reg.setText(_translate("Dialog_calc_object", "ADD REG"))
        self.pushButton_start_co.setText(_translate("Dialog_calc_object", "START"))
        self.pushButton_delete_co.setText(_translate("Dialog_calc_object", "REMOVE"))
        self.pushButton_clear_co.setText(_translate("Dialog_calc_object", "CLEAR"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_calc_object = QtWidgets.QDialog()
    ui = Ui_Dialog_calc_object()
    ui.setupUi(Dialog_calc_object)
    Dialog_calc_object.show()
    sys.exit(app.exec_())
