# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/choose_formation_map.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormationMAP(object):
    def setupUi(self, FormationMAP):
        FormationMAP.setObjectName("FormationMAP")
        FormationMAP.resize(300, 300)
        FormationMAP.setMinimumSize(QtCore.QSize(300, 300))
        self.gridLayout = QtWidgets.QGridLayout(FormationMAP)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_form_map = QtWidgets.QListWidget(FormationMAP)
        self.listWidget_form_map.setObjectName("listWidget_form_map")
        self.gridLayout.addWidget(self.listWidget_form_map, 0, 0, 1, 1)
        self.pushButton_ok_form_map = QtWidgets.QPushButton(FormationMAP)
        self.pushButton_ok_form_map.setStyleSheet("background-color: rgb(191, 255, 191);")
        self.pushButton_ok_form_map.setObjectName("pushButton_ok_form_map")
        self.gridLayout.addWidget(self.pushButton_ok_form_map, 1, 0, 1, 1)

        self.retranslateUi(FormationMAP)
        QtCore.QMetaObject.connectSlotsByName(FormationMAP)

    def retranslateUi(self, FormationMAP):
        _translate = QtCore.QCoreApplication.translate
        FormationMAP.setWindowTitle(_translate("FormationMAP", "Formation MAP"))
        self.pushButton_ok_form_map.setText(_translate("FormationMAP", "ОК"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormationMAP = QtWidgets.QWidget()
    ui = Ui_FormationMAP()
    ui.setupUi(FormationMAP)
    FormationMAP.show()
    sys.exit(app.exec_())
