# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/comment_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_comment(object):
    def setupUi(self, Form_comment):
        Form_comment.setObjectName("Form_comment")
        Form_comment.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form_comment)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(Form_comment)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form_comment)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Form_comment)
        QtCore.QMetaObject.connectSlotsByName(Form_comment)

    def retranslateUi(self, Form_comment):
        _translate = QtCore.QCoreApplication.translate
        Form_comment.setWindowTitle(_translate("Form_comment", "Comment"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_comment = QtWidgets.QWidget()
    ui = Ui_Form_comment()
    ui.setupUi(Form_comment)
    Form_comment.show()
    sys.exit(app.exec_())
