# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/corrected_model_pred.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormCorrectedModel(object):
    def setupUi(self, FormCorrectedModel):
        FormCorrectedModel.setObjectName("FormCorrectedModel")
        FormCorrectedModel.resize(493, 440)
        self.widget = QtWidgets.QWidget(FormCorrectedModel)
        self.widget.setGeometry(QtCore.QRect(6, 6, 481, 421))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_3 = QtWidgets.QLabel(self.widget)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.spinBox_int_min = QtWidgets.QSpinBox(self.widget)
        self.spinBox_int_min.setSingleStep(10)
        self.spinBox_int_min.setObjectName("spinBox_int_min")
        self.horizontalLayout.addWidget(self.spinBox_int_min)
        self.spinBox_int_max = QtWidgets.QSpinBox(self.widget)
        self.spinBox_int_max.setSingleStep(10)
        self.spinBox_int_max.setObjectName("spinBox_int_max")
        self.horizontalLayout.addWidget(self.spinBox_int_max)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.doubleSpinBox_pred_min = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_pred_min.setDecimals(3)
        self.doubleSpinBox_pred_min.setMaximum(1.0)
        self.doubleSpinBox_pred_min.setSingleStep(0.1)
        self.doubleSpinBox_pred_min.setObjectName("doubleSpinBox_pred_min")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_pred_min)
        self.doubleSpinBox_pred_max = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_pred_max.setDecimals(3)
        self.doubleSpinBox_pred_max.setMaximum(1.0)
        self.doubleSpinBox_pred_max.setSingleStep(0.1)
        self.doubleSpinBox_pred_max.setProperty("value", 1.0)
        self.doubleSpinBox_pred_max.setObjectName("doubleSpinBox_pred_max")
        self.horizontalLayout_2.addWidget(self.doubleSpinBox_pred_max)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.checkBox_compare = QtWidgets.QCheckBox(self.widget)
        self.checkBox_compare.setObjectName("checkBox_compare")
        self.horizontalLayout_3.addWidget(self.checkBox_compare)
        self.radioButton_less = QtWidgets.QRadioButton(self.widget)
        self.radioButton_less.setChecked(True)
        self.radioButton_less.setObjectName("radioButton_less")
        self.horizontalLayout_3.addWidget(self.radioButton_less)
        self.radioButton_more = QtWidgets.QRadioButton(self.widget)
        self.radioButton_more.setObjectName("radioButton_more")
        self.horizontalLayout_3.addWidget(self.radioButton_more)
        self.doubleSpinBox_value = QtWidgets.QDoubleSpinBox(self.widget)
        self.doubleSpinBox_value.setObjectName("doubleSpinBox_value")
        self.horizontalLayout_3.addWidget(self.doubleSpinBox_value)
        self.horizontalLayout_3.setStretch(3, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.listWidget_model_pred = QtWidgets.QListWidget(self.widget)
        self.listWidget_model_pred.setObjectName("listWidget_model_pred")
        self.verticalLayout.addWidget(self.listWidget_model_pred)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.pushButton_delete_pred = QtWidgets.QPushButton(self.widget)
        self.pushButton_delete_pred.setObjectName("pushButton_delete_pred")
        self.horizontalLayout_4.addWidget(self.pushButton_delete_pred)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.horizontalLayout_4.addWidget(self.buttonBox)
        self.verticalLayout.addLayout(self.horizontalLayout_4)

        self.retranslateUi(FormCorrectedModel)
        QtCore.QMetaObject.connectSlotsByName(FormCorrectedModel)

    def retranslateUi(self, FormCorrectedModel):
        _translate = QtCore.QCoreApplication.translate
        FormCorrectedModel.setWindowTitle(_translate("FormCorrectedModel", "Corrected Model Prediction"))
        self.label_3.setText(_translate("FormCorrectedModel", "Model:"))
        self.label.setText(_translate("FormCorrectedModel", "Interval:"))
        self.label_2.setText(_translate("FormCorrectedModel", "Prediction:"))
        self.checkBox_compare.setText(_translate("FormCorrectedModel", "compare"))
        self.radioButton_less.setText(_translate("FormCorrectedModel", "<"))
        self.radioButton_more.setText(_translate("FormCorrectedModel", ">"))
        self.pushButton_delete_pred.setText(_translate("FormCorrectedModel", "Сброс"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormCorrectedModel = QtWidgets.QWidget()
    ui = Ui_FormCorrectedModel()
    ui.setupUi(FormCorrectedModel)
    FormCorrectedModel.show()
    sys.exit(app.exec_())
