# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/corrected_model_pred.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormCorrectedModel(object):
    def setupUi(self, FormCorrectedModel):
        FormCorrectedModel.setObjectName("FormCorrectedModel")
        FormCorrectedModel.resize(237, 176)
        self.gridLayout = QtWidgets.QGridLayout(FormCorrectedModel)
        self.gridLayout.setObjectName("gridLayout")
        self.doubleSpinBox_pred_min = QtWidgets.QDoubleSpinBox(FormCorrectedModel)
        self.doubleSpinBox_pred_min.setDecimals(3)
        self.doubleSpinBox_pred_min.setMaximum(1.0)
        self.doubleSpinBox_pred_min.setSingleStep(0.1)
        self.doubleSpinBox_pred_min.setObjectName("doubleSpinBox_pred_min")
        self.gridLayout.addWidget(self.doubleSpinBox_pred_min, 4, 0, 1, 1)
        self.doubleSpinBox_pred_max = QtWidgets.QDoubleSpinBox(FormCorrectedModel)
        self.doubleSpinBox_pred_max.setDecimals(3)
        self.doubleSpinBox_pred_max.setMaximum(1.0)
        self.doubleSpinBox_pred_max.setSingleStep(0.1)
        self.doubleSpinBox_pred_max.setProperty("value", 1.0)
        self.doubleSpinBox_pred_max.setObjectName("doubleSpinBox_pred_max")
        self.gridLayout.addWidget(self.doubleSpinBox_pred_max, 4, 1, 1, 1)
        self.label = QtWidgets.QLabel(FormCorrectedModel)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(FormCorrectedModel)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 3, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(FormCorrectedModel)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 1)
        self.spinBox_int_min = QtWidgets.QSpinBox(FormCorrectedModel)
        self.spinBox_int_min.setSingleStep(10)
        self.spinBox_int_min.setObjectName("spinBox_int_min")
        self.gridLayout.addWidget(self.spinBox_int_min, 2, 0, 1, 1)
        self.spinBox_int_max = QtWidgets.QSpinBox(FormCorrectedModel)
        self.spinBox_int_max.setSingleStep(10)
        self.spinBox_int_max.setObjectName("spinBox_int_max")
        self.gridLayout.addWidget(self.spinBox_int_max, 2, 1, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(FormCorrectedModel)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 5, 0, 1, 2)

        self.retranslateUi(FormCorrectedModel)
        QtCore.QMetaObject.connectSlotsByName(FormCorrectedModel)

    def retranslateUi(self, FormCorrectedModel):
        _translate = QtCore.QCoreApplication.translate
        FormCorrectedModel.setWindowTitle(_translate("FormCorrectedModel", "Corrected Model Prediction"))
        self.label.setText(_translate("FormCorrectedModel", "Interval:"))
        self.label_2.setText(_translate("FormCorrectedModel", "Prediction:"))
        self.label_3.setText(_translate("FormCorrectedModel", "Model:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormCorrectedModel = QtWidgets.QWidget()
    ui = Ui_FormCorrectedModel()
    ui.setupUi(FormCorrectedModel)
    FormCorrectedModel.show()
    sys.exit(app.exec_())
