# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'feature_selection.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FeatureSelection(object):
    def setupUi(self, FeatureSelection):
        FeatureSelection.setObjectName("FeatureSelection")
        FeatureSelection.resize(565, 410)
        self.gridLayout_3 = QtWidgets.QGridLayout(FeatureSelection)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.listWidget_features = QtWidgets.QListWidget(FeatureSelection)
        self.listWidget_features.setObjectName("listWidget_features")
        self.gridLayout_2.addWidget(self.listWidget_features, 0, 0, 1, 1)
        self.plainTextEdit_results = QtWidgets.QPlainTextEdit(FeatureSelection)
        self.plainTextEdit_results.setObjectName("plainTextEdit_results")
        self.gridLayout_2.addWidget(self.plainTextEdit_results, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(FeatureSelection)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(FeatureSelection)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.comboBox_method = QtWidgets.QComboBox(FeatureSelection)
        self.comboBox_method.setObjectName("comboBox_method")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.comboBox_method.addItem("")
        self.gridLayout.addWidget(self.comboBox_method, 1, 0, 1, 1)
        self.doubleSpinBox_threshold = QtWidgets.QDoubleSpinBox(FeatureSelection)
        self.doubleSpinBox_threshold.setMaximum(1.0)
        self.doubleSpinBox_threshold.setSingleStep(0.01)
        self.doubleSpinBox_threshold.setProperty("value", 0.01)
        self.doubleSpinBox_threshold.setObjectName("doubleSpinBox_threshold")
        self.gridLayout.addWidget(self.doubleSpinBox_threshold, 1, 1, 1, 1)
        self.pushButton_select_features = QtWidgets.QPushButton(FeatureSelection)
        self.pushButton_select_features.setObjectName("pushButton_select_features")
        self.gridLayout.addWidget(self.pushButton_select_features, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(FeatureSelection)
        QtCore.QMetaObject.connectSlotsByName(FeatureSelection)

    def retranslateUi(self, FeatureSelection):
        _translate = QtCore.QCoreApplication.translate
        FeatureSelection.setWindowTitle(_translate("FeatureSelection", "Dialog"))
        self.label.setText(_translate("FeatureSelection", "method"))
        self.label_2.setText(_translate("FeatureSelection", "threshold"))
        self.comboBox_method.setItemText(0, _translate("FeatureSelection", "Quasi-constant"))
        self.comboBox_method.setItemText(1, _translate("FeatureSelection", "SelectKBest"))
        self.comboBox_method.setItemText(2, _translate("FeatureSelection", "SelectPercentile"))
        self.comboBox_method.setItemText(3, _translate("FeatureSelection", "FisherScore"))
        self.comboBox_method.setItemText(4, _translate("FeatureSelection", "F-value"))
        self.comboBox_method.setItemText(5, _translate("FeatureSelection", "Correlation"))
        self.pushButton_select_features.setText(_translate("FeatureSelection", "calc"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FeatureSelection = QtWidgets.QDialog()
    ui = Ui_FeatureSelection()
    ui.setupUi(FeatureSelection)
    FeatureSelection.show()
    sys.exit(app.exec_())
