# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/form_map_well_log.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MapWellLogging(object):
    def setupUi(self, MapWellLogging):
        MapWellLogging.setObjectName("MapWellLogging")
        MapWellLogging.resize(319, 561)
        self.gridLayout_6 = QtWidgets.QGridLayout(MapWellLogging)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.pushButton_to_excel = QtWidgets.QPushButton(MapWellLogging)
        self.pushButton_to_excel.setStyleSheet("background-color: rgb(196, 199, 255);")
        self.pushButton_to_excel.setObjectName("pushButton_to_excel")
        self.gridLayout_6.addWidget(self.pushButton_to_excel, 2, 2, 1, 1)
        self.pushButton_draw_map = QtWidgets.QPushButton(MapWellLogging)
        self.pushButton_draw_map.setStyleSheet("background-color: rgb(143, 240, 164);")
        self.pushButton_draw_map.setObjectName("pushButton_draw_map")
        self.gridLayout_6.addWidget(self.pushButton_draw_map, 2, 1, 1, 1)
        self.checkBox_all_well = QtWidgets.QCheckBox(MapWellLogging)
        self.checkBox_all_well.setObjectName("checkBox_all_well")
        self.gridLayout_6.addWidget(self.checkBox_all_well, 2, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(MapWellLogging)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.groupBox_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.listWidget_title_layer = QtWidgets.QListWidget(self.groupBox_2)
        self.listWidget_title_layer.setObjectName("listWidget_title_layer")
        self.gridLayout_5.addWidget(self.listWidget_title_layer, 0, 0, 1, 2)
        self.gridLayout_5.setColumnStretch(0, 1)
        self.gridLayout_6.addWidget(self.groupBox_2, 1, 0, 1, 3)
        self.groupBox = QtWidgets.QGroupBox(MapWellLogging)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_title_log = QtWidgets.QListWidget(self.groupBox)
        self.listWidget_title_log.setObjectName("listWidget_title_log")
        self.gridLayout.addWidget(self.listWidget_title_log, 0, 0, 1, 1)
        self.gridLayout_6.addWidget(self.groupBox, 0, 0, 1, 3)
        self.gridLayout_6.setColumnStretch(1, 1)
        self.gridLayout_6.setColumnStretch(2, 1)

        self.retranslateUi(MapWellLogging)
        QtCore.QMetaObject.connectSlotsByName(MapWellLogging)

    def retranslateUi(self, MapWellLogging):
        _translate = QtCore.QCoreApplication.translate
        MapWellLogging.setWindowTitle(_translate("MapWellLogging", "Map Well Logging"))
        self.pushButton_to_excel.setText(_translate("MapWellLogging", "EXCEL"))
        self.pushButton_draw_map.setText(_translate("MapWellLogging", "DRAW MAP"))
        self.checkBox_all_well.setToolTip(_translate("MapWellLogging", "Вкл. - по всем скважинам\n"
"Выкл. - по скважинам в пределах выбранного объекта"))
        self.checkBox_all_well.setText(_translate("MapWellLogging", "all"))
        self.groupBox_2.setTitle(_translate("MapWellLogging", "Варианты названия слоя:"))
        self.groupBox.setTitle(_translate("MapWellLogging", "Варианты названия каротажа:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MapWellLogging = QtWidgets.QWidget()
    ui = Ui_MapWellLogging()
    ui.setupUi(MapWellLogging)
    MapWellLogging.show()
    sys.exit(app.exec_())
