# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/form_upgrade_predict_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormUpgradeModel(object):
    def setupUi(self, FormUpgradeModel):
        FormUpgradeModel.setObjectName("FormUpgradeModel")
        FormUpgradeModel.resize(300, 300)
        self.gridLayout = QtWidgets.QGridLayout(FormUpgradeModel)
        self.gridLayout.setObjectName("gridLayout")
        self.listWidget_predict_model = QtWidgets.QListWidget(FormUpgradeModel)
        self.listWidget_predict_model.setObjectName("listWidget_predict_model")
        self.gridLayout.addWidget(self.listWidget_predict_model, 0, 0, 1, 2)
        self.pushButton_upgrade_model = QtWidgets.QPushButton(FormUpgradeModel)
        self.pushButton_upgrade_model.setStyleSheet("background-color: rgb(255, 239, 158);")
        self.pushButton_upgrade_model.setObjectName("pushButton_upgrade_model")
        self.gridLayout.addWidget(self.pushButton_upgrade_model, 1, 1, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(FormUpgradeModel)
        QtCore.QMetaObject.connectSlotsByName(FormUpgradeModel)

    def retranslateUi(self, FormUpgradeModel):
        _translate = QtCore.QCoreApplication.translate
        FormUpgradeModel.setWindowTitle(_translate("FormUpgradeModel", "Form Upgrade Model"))
        self.pushButton_upgrade_model.setToolTip(_translate("FormUpgradeModel", "переназначить модель"))
        self.pushButton_upgrade_model.setText(_translate("FormUpgradeModel", "UPGRADE"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormUpgradeModel = QtWidgets.QWidget()
    ui = Ui_FormUpgradeModel()
    ui.setupUi(FormUpgradeModel)
    FormUpgradeModel.show()
    sys.exit(app.exec_())
