# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\User\PycharmProjects\geo\geovel_1.0\qt\load_points.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_load_points(object):
    def setupUi(self, Form_load_points):
        Form_load_points.setObjectName("Form_load_points")
        Form_load_points.resize(305, 260)
        self.widget = QtWidgets.QWidget(Form_load_points)
        self.widget.setGeometry(QtCore.QRect(40, 30, 221, 201))
        self.widget.setObjectName("widget")
        self.formLayout = QtWidgets.QFormLayout(self.widget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.comboBox_N = QtWidgets.QComboBox(self.widget)
        self.comboBox_N.setObjectName("comboBox_N")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.comboBox_N)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox_x = QtWidgets.QComboBox(self.widget)
        self.comboBox_x.setObjectName("comboBox_x")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox_x)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_y = QtWidgets.QComboBox(self.widget)
        self.comboBox_y.setObjectName("comboBox_y")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_y)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setAlignment(QtCore.Qt.AlignBottom|QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.label_5)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.comboBox_t = QtWidgets.QComboBox(self.widget)
        self.comboBox_t.setObjectName("comboBox_t")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.comboBox_t)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.widget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.buttonBox)

        self.retranslateUi(Form_load_points)
        QtCore.QMetaObject.connectSlotsByName(Form_load_points)

    def retranslateUi(self, Form_load_points):
        _translate = QtCore.QCoreApplication.translate
        Form_load_points.setWindowTitle(_translate("Form_load_points", "Загрузка точек исследования"))
        self.label.setText(_translate("Form_load_points", "N"))
        self.label_2.setText(_translate("Form_load_points", "X"))
        self.label_3.setText(_translate("Form_load_points", "Y"))
        self.label_5.setText(_translate("Form_load_points", "Target for train data"))
        self.label_4.setText(_translate("Form_load_points", "T"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_load_points = QtWidgets.QWidget()
    ui = Ui_Form_load_points()
    ui.setupUi(Form_load_points)
    Form_load_points.show()
    sys.exit(app.exec_())
