# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\USER\PycharmProjects\geovel_1.0\qt\load_points.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_load_points(object):
    def setupUi(self, Form_load_points):
        Form_load_points.setObjectName("Form_load_points")
        Form_load_points.resize(264, 207)
        self.gridLayout_3 = QtWidgets.QGridLayout(Form_load_points)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form_load_points)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_N = QtWidgets.QComboBox(Form_load_points)
        self.comboBox_N.setObjectName("comboBox_N")
        self.gridLayout.addWidget(self.comboBox_N, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form_load_points)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_x = QtWidgets.QComboBox(Form_load_points)
        self.comboBox_x.setObjectName("comboBox_x")
        self.gridLayout.addWidget(self.comboBox_x, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(Form_load_points)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_y = QtWidgets.QComboBox(Form_load_points)
        self.comboBox_y.setObjectName("comboBox_y")
        self.gridLayout.addWidget(self.comboBox_y, 2, 1, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 2)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form_load_points)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout_2.addWidget(self.buttonBox, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 1, 1)

        self.retranslateUi(Form_load_points)
        QtCore.QMetaObject.connectSlotsByName(Form_load_points)

    def retranslateUi(self, Form_load_points):
        _translate = QtCore.QCoreApplication.translate
        Form_load_points.setWindowTitle(_translate("Form_load_points", "Загрузка точек исследования"))
        self.label.setText(_translate("Form_load_points", "N"))
        self.label_2.setText(_translate("Form_load_points", "X"))
        self.label_3.setText(_translate("Form_load_points", "Y"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_load_points = QtWidgets.QWidget()
    ui = Ui_Form_load_points()
    ui.setupUi(Form_load_points)
    Form_load_points.show()
    sys.exit(app.exec_())
