# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\mask_info_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_Mask_Info(object):
    def setupUi(self, Form_Mask_Info):
        Form_Mask_Info.setObjectName("Form_Mask_Info")
        Form_Mask_Info.resize(400, 300)
        self.gridLayout = QtWidgets.QGridLayout(Form_Mask_Info)
        self.gridLayout.setObjectName("gridLayout")
        self.textEdit = QtWidgets.QTextEdit(Form_Mask_Info)
        self.textEdit.setObjectName("textEdit")
        self.gridLayout.addWidget(self.textEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(Form_Mask_Info)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(Form_Mask_Info)
        QtCore.QMetaObject.connectSlotsByName(Form_Mask_Info)

    def retranslateUi(self, Form_Mask_Info):
        _translate = QtCore.QCoreApplication.translate
        Form_Mask_Info.setWindowTitle(_translate("Form_Mask_Info", "Mask Info"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_Mask_Info = QtWidgets.QWidget()
    ui = Ui_Form_Mask_Info()
    ui.setupUi(Form_Mask_Info)
    Form_Mask_Info.show()
    sys.exit(app.exec_())
