# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'parameter_dependence.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog_PDP(object):
    def setupUi(self, Dialog_PDP):
        Dialog_PDP.setObjectName("Dialog_PDP")
        Dialog_PDP.resize(260, 111)
        self.gridLayout_2 = QtWidgets.QGridLayout(Dialog_PDP)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_pdp_2 = QtWidgets.QComboBox(Dialog_PDP)
        self.comboBox_pdp_2.setCurrentText("")
        self.comboBox_pdp_2.setObjectName("comboBox_pdp_2")
        self.gridLayout.addWidget(self.comboBox_pdp_2, 1, 1, 1, 2)
        self.label = QtWidgets.QLabel(Dialog_PDP)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_pdp = QtWidgets.QComboBox(Dialog_PDP)
        self.comboBox_pdp.setCurrentText("")
        self.comboBox_pdp.setObjectName("comboBox_pdp")
        self.gridLayout.addWidget(self.comboBox_pdp, 0, 1, 1, 2)
        self.pushButton_pdp = QtWidgets.QPushButton(Dialog_PDP)
        self.pushButton_pdp.setStyleSheet("background-color: rgb(255, 255, 191);")
        self.pushButton_pdp.setObjectName("pushButton_pdp")
        self.gridLayout.addWidget(self.pushButton_pdp, 2, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(Dialog_PDP)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.checkBox_2_params = QtWidgets.QCheckBox(Dialog_PDP)
        self.checkBox_2_params.setObjectName("checkBox_2_params")
        self.gridLayout.addWidget(self.checkBox_2_params, 2, 1, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Dialog_PDP)
        QtCore.QMetaObject.connectSlotsByName(Dialog_PDP)

    def retranslateUi(self, Dialog_PDP):
        _translate = QtCore.QCoreApplication.translate
        Dialog_PDP.setWindowTitle(_translate("Dialog_PDP", "Parameter Dependence"))
        self.label.setText(_translate("Dialog_PDP", "parameter 1"))
        self.pushButton_pdp.setText(_translate("Dialog_PDP", "draw"))
        self.label_2.setText(_translate("Dialog_PDP", "parameter 2"))
        self.checkBox_2_params.setText(_translate("Dialog_PDP", "2 params"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_PDP = QtWidgets.QDialog()
    ui = Ui_Dialog_PDP()
    ui.setupUi(Dialog_PDP)
    Dialog_PDP.show()
    sys.exit(app.exec_())
