# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/point_param_graph_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_GraphParam(object):
    def setupUi(self, GraphParam):
        GraphParam.setObjectName("GraphParam")
        GraphParam.resize(1600, 1080)
        self.gridLayout = QtWidgets.QGridLayout(GraphParam)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(GraphParam)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listWidget_param = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_param.setObjectName("listWidget_param")
        self.horizontalLayout_3.addWidget(self.listWidget_param)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_param_all = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_param_all.setText("")
        self.checkBox_param_all.setChecked(True)
        self.checkBox_param_all.setObjectName("checkBox_param_all")
        self.verticalLayout_2.addWidget(self.checkBox_param_all)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem)
        self.horizontalLayout_3.addLayout(self.verticalLayout_2)
        self.listWidget_point = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_point.setObjectName("listWidget_point")
        self.horizontalLayout_3.addWidget(self.listWidget_point)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.checkBox_point_all = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_point_all.setText("")
        self.checkBox_point_all.setChecked(True)
        self.checkBox_point_all.setObjectName("checkBox_point_all")
        self.verticalLayout_3.addWidget(self.checkBox_point_all)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem1)
        self.horizontalLayout_3.addLayout(self.verticalLayout_3)
        self.listWidget_well = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_well.setObjectName("listWidget_well")
        self.horizontalLayout_3.addWidget(self.listWidget_well)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.checkBox_well_all = QtWidgets.QCheckBox(self.frame_2)
        self.checkBox_well_all.setText("")
        self.checkBox_well_all.setChecked(True)
        self.checkBox_well_all.setObjectName("checkBox_well_all")
        self.verticalLayout_4.addWidget(self.checkBox_well_all)
        spacerItem2 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_4.addItem(spacerItem2)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem3)
        self.horizontalLayout_3.setStretch(6, 1)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(GraphParam)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(GraphParam)
        QtCore.QMetaObject.connectSlotsByName(GraphParam)

    def retranslateUi(self, GraphParam):
        _translate = QtCore.QCoreApplication.translate
        GraphParam.setWindowTitle(_translate("GraphParam", "GraphParam"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    GraphParam = QtWidgets.QWidget()
    ui = Ui_GraphParam()
    ui.setupUi(GraphParam)
    GraphParam.show()
    sys.exit(app.exec_())
