# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/qc_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormQC(object):
    def setupUi(self, FormQC):
        FormQC.setObjectName("FormQC")
        FormQC.resize(400, 300)
        self.gridLayout_4 = QtWidgets.QGridLayout(FormQC)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_qc_profile = QtWidgets.QPushButton(FormQC)
        self.pushButton_qc_profile.setStyleSheet("background-color: rgb(255, 224, 161);")
        self.pushButton_qc_profile.setObjectName("pushButton_qc_profile")
        self.gridLayout.addWidget(self.pushButton_qc_profile, 0, 0, 1, 1)
        self.pushButton_qc_object = QtWidgets.QPushButton(FormQC)
        self.pushButton_qc_object.setStyleSheet("background-color: rgb(255, 200, 106);")
        self.pushButton_qc_object.setObjectName("pushButton_qc_object")
        self.gridLayout.addWidget(self.pushButton_qc_object, 1, 0, 1, 1)
        self.pushButton_qc_well = QtWidgets.QPushButton(FormQC)
        self.pushButton_qc_well.setStyleSheet("background-color: rgb(238, 255, 184);")
        self.pushButton_qc_well.setObjectName("pushButton_qc_well")
        self.gridLayout.addWidget(self.pushButton_qc_well, 2, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.comboBox_snr_mode = QtWidgets.QComboBox(FormQC)
        self.comboBox_snr_mode.setObjectName("comboBox_snr_mode")
        self.comboBox_snr_mode.addItem("")
        self.comboBox_snr_mode.addItem("")
        self.comboBox_snr_mode.addItem("")
        self.comboBox_snr_mode.addItem("")
        self.comboBox_snr_mode.addItem("")
        self.comboBox_snr_mode.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_snr_mode, 1, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 1, 1, 1, 1)
        self.listWidget = QtWidgets.QListWidget(FormQC)
        self.listWidget.setObjectName("listWidget")
        self.gridLayout_3.addWidget(self.listWidget, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(FormQC)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 2)
        self.gridLayout_4.addLayout(self.gridLayout_3, 0, 0, 1, 1)

        self.retranslateUi(FormQC)
        QtCore.QMetaObject.connectSlotsByName(FormQC)

    def retranslateUi(self, FormQC):
        _translate = QtCore.QCoreApplication.translate
        FormQC.setWindowTitle(_translate("FormQC", "Quality Control"))
        self.pushButton_qc_profile.setText(_translate("FormQC", "PROFILE"))
        self.pushButton_qc_object.setText(_translate("FormQC", "OBJECT"))
        self.pushButton_qc_well.setText(_translate("FormQC", "WELL"))
        self.comboBox_snr_mode.setItemText(0, _translate("FormQC", "global_proxy"))
        self.comboBox_snr_mode.setItemText(1, _translate("FormQC", "global_noise_subtracted"))
        self.comboBox_snr_mode.setItemText(2, _translate("FormQC", "windowed_manual"))
        self.comboBox_snr_mode.setItemText(3, _translate("FormQC", "peak_manual"))
        self.comboBox_snr_mode.setItemText(4, _translate("FormQC", "windowed_auto"))
        self.comboBox_snr_mode.setItemText(5, _translate("FormQC", "peak_auto"))
        self.label.setText(_translate("FormQC", "QC-panel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormQC = QtWidgets.QWidget()
    ui = Ui_FormQC()
    ui.setupUi(FormQC)
    FormQC.show()
    sys.exit(app.exec_())
