# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\qt\rem_db_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_rem_db(object):
    def setupUi(self, rem_db):
        rem_db.setObjectName("rem_db")
        rem_db.resize(468, 180)
        self.layoutWidget = QtWidgets.QWidget(rem_db)
        self.layoutWidget.setGeometry(QtCore.QRect(40, 50, 365, 66))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_7.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setStyleSheet("background-color: rgb(191, 255, 191);")
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 0, 1, 1)
        self.comboBox_profile_rem = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_profile_rem.sizePolicy().hasHeightForWidth())
        self.comboBox_profile_rem.setSizePolicy(sizePolicy)
        self.comboBox_profile_rem.setObjectName("comboBox_profile_rem")
        self.gridLayout_2.addWidget(self.comboBox_profile_rem, 0, 1, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout_2, 1, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.comboBox_object_rem = QtWidgets.QComboBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox_object_rem.sizePolicy().hasHeightForWidth())
        self.comboBox_object_rem.setSizePolicy(sizePolicy)
        self.comboBox_object_rem.setObjectName("comboBox_object_rem")
        self.gridLayout.addWidget(self.comboBox_object_rem, 0, 1, 1, 1)
        self.comboBox_research_rem = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_research_rem.setObjectName("comboBox_research_rem")
        self.gridLayout.addWidget(self.comboBox_research_rem, 0, 2, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setStyleSheet("background-color: rgb(191, 255, 191);")
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_5.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_5, 0, 0, 1, 1)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_unload_obj_rem = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_unload_obj_rem.setStyleSheet("background-color: rgb(255, 255, 0);")
        self.pushButton_unload_obj_rem.setObjectName("pushButton_unload_obj_rem")
        self.gridLayout_3.addWidget(self.pushButton_unload_obj_rem, 0, 1, 1, 1)
        self.pushButton_load_obj_rem = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_load_obj_rem.setStyleSheet("background-color: rgb(0, 255, 0);")
        self.pushButton_load_obj_rem.setObjectName("pushButton_load_obj_rem")
        self.gridLayout_3.addWidget(self.pushButton_load_obj_rem, 0, 0, 1, 1)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout_3.addLayout(self.gridLayout_4, 1, 0, 1, 1)
        self.pushButton_delete_obj_rem = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_delete_obj_rem.setStyleSheet("background-color: rgb(255, 0, 0);")
        self.pushButton_delete_obj_rem.setObjectName("pushButton_delete_obj_rem")
        self.gridLayout_3.addWidget(self.pushButton_delete_obj_rem, 2, 0, 1, 2)
        self.gridLayout_6.addLayout(self.gridLayout_3, 1, 0, 1, 1)
        self.gridLayout_7.addLayout(self.gridLayout_6, 0, 1, 1, 1)

        self.retranslateUi(rem_db)
        QtCore.QMetaObject.connectSlotsByName(rem_db)

    def retranslateUi(self, rem_db):
        _translate = QtCore.QCoreApplication.translate
        rem_db.setWindowTitle(_translate("rem_db", "RemoteDB"))
        self.label_5.setText(_translate("rem_db", "Профиль:"))
        self.label_4.setText(_translate("rem_db", "Объект:"))
        self.pushButton_unload_obj_rem.setToolTip(_translate("rem_db", "Выгрузить объект с локальной БД на удаленную"))
        self.pushButton_unload_obj_rem.setText(_translate("rem_db", "Выгрузить"))
        self.pushButton_load_obj_rem.setToolTip(_translate("rem_db", "Загрузить объект с удаленной БД на локальную"))
        self.pushButton_load_obj_rem.setText(_translate("rem_db", "Загрузить"))
        self.pushButton_delete_obj_rem.setToolTip(_translate("rem_db", "Удалить объект "))
        self.pushButton_delete_obj_rem.setText(_translate("rem_db", "Удалить"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    rem_db = QtWidgets.QWidget()
    ui = Ui_rem_db()
    ui.setupUi(rem_db)
    rem_db.show()
    sys.exit(app.exec_())
