# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/rename_model.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_FormRenameModel(object):
    def setupUi(self, FormRenameModel):
        FormRenameModel.setObjectName("FormRenameModel")
        FormRenameModel.resize(496, 74)
        self.gridLayout = QtWidgets.QGridLayout(FormRenameModel)
        self.gridLayout.setObjectName("gridLayout")
        self.lineEdit = QtWidgets.QLineEdit(FormRenameModel)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 0, 1, 1)
        self.buttonBox = QtWidgets.QDialogButtonBox(FormRenameModel)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.gridLayout.addWidget(self.buttonBox, 1, 0, 1, 1)

        self.retranslateUi(FormRenameModel)
        QtCore.QMetaObject.connectSlotsByName(FormRenameModel)

    def retranslateUi(self, FormRenameModel):
        _translate = QtCore.QCoreApplication.translate
        FormRenameModel.setWindowTitle(_translate("FormRenameModel", "Rename Model"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    FormRenameModel = QtWidgets.QWidget()
    ui = Ui_FormRenameModel()
    ui.setupUi(FormRenameModel)
    FormRenameModel.show()
    sys.exit(app.exec_())
