# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_model_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_ModelParams(object):
    def setupUi(self, Form_ModelParams):
        Form_ModelParams.setObjectName("Form_ModelParams")
        Form_ModelParams.resize(567, 504)
        self.gridLayout_4 = QtWidgets.QGridLayout(Form_ModelParams)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form_ModelParams)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_count = QtWidgets.QLabel(Form_ModelParams)
        self.label_count.setObjectName("label_count")
        self.gridLayout.addWidget(self.label_count, 3, 0, 1, 1)
        self.label_crl = QtWidgets.QLabel(Form_ModelParams)
        self.label_crl.setObjectName("label_crl")
        self.gridLayout.addWidget(self.label_crl, 1, 0, 1, 1)
        self.label_signal = QtWidgets.QLabel(Form_ModelParams)
        self.label_signal.setObjectName("label_signal")
        self.gridLayout.addWidget(self.label_signal, 2, 0, 1, 1)
        self.listWidget_parameters = QtWidgets.QListWidget(Form_ModelParams)
        self.listWidget_parameters.setObjectName("listWidget_parameters")
        self.gridLayout.addWidget(self.listWidget_parameters, 4, 0, 1, 1)
        self.line = QtWidgets.QFrame(Form_ModelParams)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.gridLayout.addWidget(self.line, 4, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout, 0, 0, 1, 1)
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_crl_2 = QtWidgets.QLabel(Form_ModelParams)
        self.label_crl_2.setObjectName("label_crl_2")
        self.gridLayout_2.addWidget(self.label_crl_2, 1, 0, 1, 1)
        self.label_signal_2 = QtWidgets.QLabel(Form_ModelParams)
        self.label_signal_2.setObjectName("label_signal_2")
        self.gridLayout_2.addWidget(self.label_signal_2, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form_ModelParams)
        self.label_2.setObjectName("label_2")
        self.gridLayout_2.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_count_2 = QtWidgets.QLabel(Form_ModelParams)
        self.label_count_2.setObjectName("label_count_2")
        self.gridLayout_2.addWidget(self.label_count_2, 3, 0, 1, 1)
        self.listWidget_parameters_2 = QtWidgets.QListWidget(Form_ModelParams)
        self.listWidget_parameters_2.setObjectName("listWidget_parameters_2")
        self.gridLayout_2.addWidget(self.listWidget_parameters_2, 4, 0, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_2, 0, 1, 1, 1)
        self.label_common_param = QtWidgets.QLabel(Form_ModelParams)
        self.label_common_param.setObjectName("label_common_param")
        self.gridLayout_4.addWidget(self.label_common_param, 1, 0, 1, 1)
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButton_add_reg = QtWidgets.QPushButton(Form_ModelParams)
        self.pushButton_add_reg.setStyleSheet("background-color: rgb(255, 255, 191);")
        self.pushButton_add_reg.setObjectName("pushButton_add_reg")
        self.gridLayout_3.addWidget(self.pushButton_add_reg, 0, 0, 1, 1)
        self.pushButton_add_class = QtWidgets.QPushButton(Form_ModelParams)
        self.pushButton_add_class.setStyleSheet("background-color: rgb(255, 163, 72);")
        self.pushButton_add_class.setObjectName("pushButton_add_class")
        self.gridLayout_3.addWidget(self.pushButton_add_class, 0, 1, 1, 1)
        self.gridLayout_4.addLayout(self.gridLayout_3, 1, 1, 1, 1)

        self.retranslateUi(Form_ModelParams)
        QtCore.QMetaObject.connectSlotsByName(Form_ModelParams)

    def retranslateUi(self, Form_ModelParams):
        _translate = QtCore.QCoreApplication.translate
        Form_ModelParams.setWindowTitle(_translate("Form_ModelParams", "Model Parameters"))
        self.label.setText(_translate("Form_ModelParams", "Model: "))
        self.label_count.setText(_translate("Form_ModelParams", "Params count: "))
        self.label_crl.setText(_translate("Form_ModelParams", "Exception CRL: "))
        self.label_signal.setText(_translate("Form_ModelParams", "Exception Signal: "))
        self.label_crl_2.setText(_translate("Form_ModelParams", "Exception CRL: "))
        self.label_signal_2.setText(_translate("Form_ModelParams", "Exception Signal: "))
        self.label_2.setText(_translate("Form_ModelParams", "Model: "))
        self.label_count_2.setText(_translate("Form_ModelParams", "Params count: "))
        self.label_common_param.setText(_translate("Form_ModelParams", "TextLabel"))
        self.pushButton_add_reg.setText(_translate("Form_ModelParams", "add model_reg"))
        self.pushButton_add_class.setText(_translate("Form_ModelParams", "add model class"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_ModelParams = QtWidgets.QWidget()
    ui = Ui_Form_ModelParams()
    ui.setupUi(Form_ModelParams)
    Form_ModelParams.show()
    sys.exit(app.exec_())
