# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'show_model_params.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form_ModelParams(object):
    def setupUi(self, Form_ModelParams):
        Form_ModelParams.setObjectName("Form_ModelParams")
        Form_ModelParams.resize(296, 493)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form_ModelParams)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form_ModelParams)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.listWidget_parameters = QtWidgets.QListWidget(Form_ModelParams)
        self.listWidget_parameters.setObjectName("listWidget_parameters")
        self.gridLayout.addWidget(self.listWidget_parameters, 1, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form_ModelParams)
        QtCore.QMetaObject.connectSlotsByName(Form_ModelParams)

    def retranslateUi(self, Form_ModelParams):
        _translate = QtCore.QCoreApplication.translate
        Form_ModelParams.setWindowTitle(_translate("Form_ModelParams", "Model Parameters"))
        self.label.setText(_translate("Form_ModelParams", "Model params:"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form_ModelParams = QtWidgets.QWidget()
    ui = Ui_Form_ModelParams()
    ui.setupUi(Form_ModelParams)
    Form_ModelParams.show()
    sys.exit(app.exec_())
