# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/slice_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_SliceForm(object):
    def setupUi(self, SliceForm):
        SliceForm.setObjectName("SliceForm")
        SliceForm.resize(924, 629)
        self.gridLayout_10 = QtWidgets.QGridLayout(SliceForm)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.gridLayout_11 = QtWidgets.QGridLayout()
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.spinBox_slice = QtWidgets.QSpinBox(SliceForm)
        self.spinBox_slice.setMinimum(1)
        self.spinBox_slice.setMaximum(512)
        self.spinBox_slice.setProperty("value", 20)
        self.spinBox_slice.setObjectName("spinBox_slice")
        self.gridLayout_11.addWidget(self.spinBox_slice, 0, 0, 1, 1)
        self.comboBox_cmap = QtWidgets.QComboBox(SliceForm)
        self.comboBox_cmap.setObjectName("comboBox_cmap")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.comboBox_cmap.addItem("")
        self.gridLayout_11.addWidget(self.comboBox_cmap, 1, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem, 3, 0, 1, 1)
        self.pushButton_export = QtWidgets.QPushButton(SliceForm)
        self.pushButton_export.setStyleSheet("background-color: rgb(255, 170, 127);")
        self.pushButton_export.setObjectName("pushButton_export")
        self.gridLayout_11.addWidget(self.pushButton_export, 2, 0, 1, 1)
        self.gridLayout_10.addLayout(self.gridLayout_11, 0, 1, 1, 1)
        self.gridLayout_9 = QtWidgets.QGridLayout()
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.verticalLayout_slice = QtWidgets.QVBoxLayout()
        self.verticalLayout_slice.setObjectName("verticalLayout_slice")
        self.gridLayout_8.addLayout(self.verticalLayout_slice, 0, 0, 1, 1)
        self.gridLayout_9.addLayout(self.gridLayout_8, 0, 0, 1, 1)
        self.gridLayout_9.setRowStretch(0, 4)
        self.gridLayout_10.addLayout(self.gridLayout_9, 0, 0, 1, 1)
        self.gridLayout_10.setColumnStretch(0, 4)
        self.gridLayout_10.setColumnStretch(1, 1)

        self.retranslateUi(SliceForm)
        QtCore.QMetaObject.connectSlotsByName(SliceForm)

    def retranslateUi(self, SliceForm):
        _translate = QtCore.QCoreApplication.translate
        SliceForm.setWindowTitle(_translate("SliceForm", "Slice Form"))
        self.comboBox_cmap.setCurrentText(_translate("SliceForm", "binary"))
        self.comboBox_cmap.setItemText(0, _translate("SliceForm", "gray"))
        self.comboBox_cmap.setItemText(1, _translate("SliceForm", "gray_r"))
        self.comboBox_cmap.setItemText(2, _translate("SliceForm", "binary"))
        self.comboBox_cmap.setItemText(3, _translate("SliceForm", "bone"))
        self.comboBox_cmap.setItemText(4, _translate("SliceForm", "jet"))
        self.comboBox_cmap.setItemText(5, _translate("SliceForm", "rainbow"))
        self.comboBox_cmap.setItemText(6, _translate("SliceForm", "turbo"))
        self.comboBox_cmap.setItemText(7, _translate("SliceForm", "hsv"))
        self.comboBox_cmap.setItemText(8, _translate("SliceForm", "seismic"))
        self.comboBox_cmap.setItemText(9, _translate("SliceForm", "coolwarm"))
        self.comboBox_cmap.setItemText(10, _translate("SliceForm", "RdBu"))
        self.comboBox_cmap.setItemText(11, _translate("SliceForm", "bwr"))
        self.comboBox_cmap.setItemText(12, _translate("SliceForm", "viridis"))
        self.comboBox_cmap.setItemText(13, _translate("SliceForm", "plasma"))
        self.comboBox_cmap.setItemText(14, _translate("SliceForm", "inferno"))
        self.comboBox_cmap.setItemText(15, _translate("SliceForm", "magma"))
        self.comboBox_cmap.setItemText(16, _translate("SliceForm", "cividis"))
        self.comboBox_cmap.setItemText(17, _translate("SliceForm", "hot"))
        self.comboBox_cmap.setItemText(18, _translate("SliceForm", "afmhot"))
        self.comboBox_cmap.setItemText(19, _translate("SliceForm", "Spectral"))
        self.pushButton_export.setText(_translate("SliceForm", "Export Slice"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    SliceForm = QtWidgets.QWidget()
    ui = Ui_SliceForm()
    ui.setupUi(SliceForm)
    SliceForm.show()
    sys.exit(app.exec_())
