# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'qt/tsne_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_TSNE_PCA(object):
    def setupUi(self, TSNE_PCA):
        TSNE_PCA.setObjectName("TSNE_PCA")
        TSNE_PCA.resize(1600, 1080)
        self.gridLayout = QtWidgets.QGridLayout(TSNE_PCA)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_2 = QtWidgets.QFrame(TSNE_PCA)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.frame_2)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.listWidget_point = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_point.setObjectName("listWidget_point")
        self.horizontalLayout_3.addWidget(self.listWidget_point)
        self.listWidget_checkbox_well = QtWidgets.QListWidget(self.frame_2)
        self.listWidget_checkbox_well.setObjectName("listWidget_checkbox_well")
        self.horizontalLayout_3.addWidget(self.listWidget_checkbox_well)
        self.frame_3 = QtWidgets.QFrame(self.frame_2)
        self.frame_3.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_3)
        self.verticalLayout.setObjectName("verticalLayout")
        self.radioButton_tsne = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_tsne.setChecked(True)
        self.radioButton_tsne.setObjectName("radioButton_tsne")
        self.verticalLayout.addWidget(self.radioButton_tsne)
        self.radioButton_pca = QtWidgets.QRadioButton(self.frame_3)
        self.radioButton_pca.setObjectName("radioButton_pca")
        self.verticalLayout.addWidget(self.radioButton_pca)
        self.checkBox_standart = QtWidgets.QCheckBox(self.frame_3)
        self.checkBox_standart.setChecked(True)
        self.checkBox_standart.setObjectName("checkBox_standart")
        self.verticalLayout.addWidget(self.checkBox_standart)
        self.horizontalLayout_3.addWidget(self.frame_3)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.horizontalLayout_3.setStretch(2, 1)
        self.horizontalLayout_3.setStretch(3, 5)
        self.gridLayout.addWidget(self.frame_2, 1, 0, 1, 1)
        self.frame = QtWidgets.QFrame(TSNE_PCA)
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.frame)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.verticalLayout_graph = QtWidgets.QVBoxLayout()
        self.verticalLayout_graph.setObjectName("verticalLayout_graph")
        self.horizontalLayout_2.addLayout(self.verticalLayout_graph)
        self.gridLayout.addWidget(self.frame, 0, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 3)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(TSNE_PCA)
        QtCore.QMetaObject.connectSlotsByName(TSNE_PCA)

    def retranslateUi(self, TSNE_PCA):
        _translate = QtCore.QCoreApplication.translate
        TSNE_PCA.setWindowTitle(_translate("TSNE_PCA", "TSNE PCA"))
        self.radioButton_tsne.setText(_translate("TSNE_PCA", "TSNE"))
        self.radioButton_pca.setText(_translate("TSNE_PCA", "PCA"))
        self.checkBox_standart.setText(_translate("TSNE_PCA", "standart"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    TSNE_PCA = QtWidgets.QWidget()
    ui = Ui_TSNE_PCA()
    ui.setupUi(TSNE_PCA)
    TSNE_PCA.show()
    sys.exit(app.exec_())
